#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'magenta'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    backgound = 'transparent'
    foreground = 'p:purple'

    [blocks.segments.properties]
    style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#6c6c6c'
    background = 'transparent'
    template = '{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed)}}*{{end}}'

    [blocks.segments.properties]
      fetch_status = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}p:purple{{end}}",
    ]
    background = 'transparent'
    template = "󰞷"

[palette]
purple = '#9333ea'

